apiVersion : apps/v1
kind: Deployment
metadata:
  name: bryanpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bryanpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: bryanpipelinesjavascriptdocker 
    spec:
      containers:
        - name: bryanpipelinesjavascriptdocker 
          image: jalafoundationcontainer01.azurecr.io/bryanpipelinesjavascriptdocker
          ports:
          - containerPort: 8080